# Generated by Django 5.2.6 on 2025-11-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, help_text='Invoice/Bill number', max_length=100, null=True),
        ),
    ]
