# Generated by Django 5.2.6 on 2025-11-16 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bill_invoice_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['user', 'invoice_number', 'vendor'], name='bills_bill_user_id_ad72c2_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['user', 'bill_date'], name='bills_bill_user_id_c20425_idx'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number__isnull', False), ('vendor__isnull', False)), fields=('user', 'invoice_number', 'vendor'), name='unique_invoice_per_vendor_per_user'),
        ),
    ]
