# Generated by Django 5.2.6 on 2025-11-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_bill_bills_bill_user_id_ad72c2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='line_items',
            field=models.JSONField(blank=True, default=list, help_text='List of items/goods in the bill'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('INR', 'Indian Rupee'), ('NPR', 'Nepali Rupee')], default='USD', max_length=3),
        ),
    ]
