# Generated by Django 5.2.6 on 2025-12-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_bill_account_type_bill_is_debit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('INR', 'Indian Rupee'), ('NPR', 'Nepali Rupee')], default='NPR', max_length=3),
        ),
    ]
