# Generated by Django 5.2.6 on 2025-12-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_alter_bill_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='amount_npr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to NPR', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Exchange rate to NPR at bill date', max_digits=10),
        ),
    ]
