# Generated by Django 5.2.7 on 2025-12-12 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_bill_amount_npr_bill_exchange_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='is_recurring',
            new_name='is_reimbursable',
        ),
    ]
