# Generated by Django 5.2.6 on 2025-11-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
