# Generated by Django 5.2.7 on 2025-12-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='business_type',
            field=models.CharField(blank=True, help_text='Type of Business', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company/Business Name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pan_vat_number',
            field=models.CharField(blank=True, help_text='PAN/VAT Registration Number', max_length=50, null=True),
        ),
    ]
