# Generated by Django 5.2.6 on 2025-11-14 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditreport',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditreport',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate'),
        ),
    ]
